<?php
/**
 *
 * @package         Super Deals
 * @version         1.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   August 2012
 * @Modified By     Murali B
 * @Modified Date   Mar 29 2014
 *
 * */
?>
<?php
/**
 * Template for displaying product price in different places (products grid, product view page etc)
 *
 * @see Mage_Catalog_Block_Product_Abstract
 */
?>
<?php
/* Count for timer calculation declared here */
$_productsCollections	= $this->getProductCollection();
$_helper 		= $this->helper('catalog/output');
$_coreHelper 		= $this->helper('core');
$count		 	= Mage::helper('superdeals')->getOfferSlider();
?>

<?php
$STORE_CONFIG_DEALS_ENABLED  = Mage::getStoreConfig('superdeals/superdeals_group/deals_enable');
$dealsEnable  				 = Mage::helper('core/data')->isModuleEnabled('Apptha_Superdeals');
$dealsEnable 				 = intval($dealsEnable);
$STORE_CONFIG_SLIDER_ENABLED = Mage::getStoreConfig('superdeals/slider/enable_slide');
$advanceOption				 = Mage::getStoreConfig('advanced/modules_disable_output/Apptha_Superdeals');
$advanceOption 				 = intval($advanceOption);
?>
<?php if($_productsCollections->count()):?>
<?php if (($STORE_CONFIG_DEALS_ENABLED == 1) && ($STORE_CONFIG_SLIDER_ENABLED == 1) && ( $dealsEnable == 1)&& ( $advanceOption == 0)): ?>
<script type="text/javascript">

Event.observe(window, 'dom:loaded', function() {
	var primaryShow = new protoShow('primary-show', {
			captions		: false,
			controls		: true,
			transitionType		: "slide"

	});
});

document.observe('dom:loaded', function() {
    // reference ID of our show container
    var show = new protoShow('primary-show');
});
</script>
<div class="deal_slider">
<div id="primary-show" class="transition-slide">
	<a href="javascript:void(0)"
		onclick="document.getElementById('primary-show').style.display='none'"><span
		class="close"></span> </a>
	<div class="primary-show-container">

		<h2 class="banner_title">
		<?php echo $this->__('Have you checked out this offer?') ?>
		</h2>

		<ul class="show">
		<?php foreach ($_productsCollections as $_products): ?>
		<?php		// Display the saving amount here
		$savingsdollarvalue = ($_products->getPrice() - $_products->getFinalPrice());
		$original_price 	= $_products->getPrice(); //get orginal price
		$discount_price 	= $_products->getFinalPrice(); //get the discount amount
		$savings			= $original_price - $discount_price; //get the saving amount from orginal price - discount price
		$savings_percentage = round(($savings / $original_price) * 100, 0); //get discount Percentage
		$productType 		= $_products->getTypeID();?>
			<li class="slide">
				<div class="banner_slide_image">
					<a href="<?php echo $_products->getProductUrl() ?>"
						title="<?php echo $this->stripTags($this->getImageLabel($_products, 'small_image'), null, true) ?>"
						class="product-image"><img
						src="<?php echo $this->helper('catalog/image')->init($_products, 'small_image')->resize(65); ?>"
						width="65" height="65"
						alt="<?php echo $this->stripTags($this->getImageLabel($_products, 'small_image'), null, true) ?>" />
					</a>
				</div>
				<div class="banner_slide_desc">
					<h2 class="product-name">
						<a href="<?php echo $_products->getProductUrl() ?>"
							title="<?php echo $this->stripTags($_products->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_products, $_products->getName(), 'name') ?>
						</a>
					</h2>
					<p class="special-price">
						<span class="price-label"><?php echo $this->__('Discount:') ?> </span>
						<span class="price"> <?php echo $savings_percentage, '%'; //display discount amount ?>
						</span>
					</p>
				</div>
			</li>
			<?php  endforeach; ?>
		</ul>




	</div>

</div></div>
			<?php endif ?>
			<?php endif ?>